export const SET_ACTIVE_MENU = 'SET_ACTIVE_MENU'
export const REPOSITION_CATEGORY = 'REPOSITION_CATEGORY'
export const MOVE_PRODUCT_CATEGORY = 'MOVE_PRODUCT_CATEGORY'
export const SET_USER = 'SET_USER'
export const SET_TOKEN = 'SET_TOKEN'

export const FETCH_USER = 'FETCH_USER'
export const GET_PUBLIC_FOLDERS = 'GET_PUBLIC_FOLDERS'
