export const SET_ACTIVE_MENU = 'SET_ACTIVE_MENU'
export const REPOSITION_CATEGORY = 'REPOSITION_CATEGORY'
export const MOVE_PRODUCT_CATEGORY = 'MOVE_PRODUCT_CATEGORY'

export const GET_MEETING_ROOMS = 'GET_MEETING_ROOMS'
export const SET_MEETING_ROOMS = 'SET_MEETING_ROOMS'
