export const SET_CURRENT_FOLDER = 'SET_CURRENT_FOLDER'
export const TOGGLE_DOCUMENT_SELECTION = 'TOGGLE_DOCUMENT_SELECTION'
export const TOGGLE_FOLDER_SELECTION = 'TOGGLE_FOLDER_SELECTION'
export const TOGGLE_FILE_ITEM_SELECTION = 'TOGGLE_FILE_ITEM_SELECTION'

export const SELECT_ALL_FILES = 'SELECT_ALL_FILES'
export const CLEAR_ALL_FILES = 'CLEAR_ALL_FILES'
export const DELETE_SELECTED = 'DELETE_SELECTED'
export const UPDATE_DOCUMENT_NAME = 'UPDATE_DOCUMENT_NAME'
export const UPDATE_FOLDER_NAME = 'UPDATE_FOLDER_NAME'

export const NEW_FOLDER = 'NEW_FOLDER'
export const DELETE_DOCUMENT = 'DELETE_DOCUMENT'
export const DELETE_FOLDER = 'DELETE_FOLDER'
export const COPY_SELECTED = 'COPY_SELECTED'
export const MOVE_SELECTED = 'MOVE_SELECTED'
export const REFRESH_FOLDER = 'REFRESH_FOLDER'

export const GET_USER_ALL_FOLDERS = 'GET_USER_ALL_FOLDERS'
