export const SET_CURRENT_FOLDER = 'SET_CURRENT_FOLDER'
export const TOGGLE_DOCUMENT_SELECTION = 'TOGGLE_DOCUMENT_SELECTION'
export const SELECT_ALL_DOCUMENTS = 'SELECT_ALL_DOCUMENTS'
export const CLEAR_DOCUMENT_SELECTION = 'CLEAR_ALL_DOCUMENT_SELECTION'
