export const GET_MEETINGS = 'GET_MEETINGS'
export const SET_MEETINGS = 'SET_MEETINGS'
export const CREATE_MEETING = 'CREATE_MEETING'
export const UPDATE_MEETING = 'UPDATE_MEETING'
export const DELETE_MEETING = 'DELETE_MEETING'

export const SET_TEMP_MEETING = 'SET_TEMP_MEETING'
