export const GET_MEETINGS = 'GET_MEETINGS'
export const SET_MEETINGS = 'SET_MEETINGS'
export const DELETE_MEETING = 'DELETE_MEETING'

export const SET_TEMP_MEETING = 'SET_TEMP_MEETING'

export const SET_TEMP_MEETING_STARTED_AT = 'SET_TEMP_MEETING_STARTED_AT'
export const SET_TEMP_MEETING_ENDED_AT = 'SET_TEMP_MEETING_ENDED_AT'

export const STORE_MEETING = 'CREATE_MEETING'
export const UPDATE_MEETING = 'UPDATE_MEETING'
