export const SET_MEETING_ROOM_BOOKINGS = 'SET_MEETING_ROOM_BOOKINGS'
export const GET_MEETING_ROOM_BOOKINGS = 'GET_MEETING_ROOM_BOOKINGS'
export const GET_DAY_BOOKINGS = 'GET_DAY_BOOKINGS'

export const SET_BOOKING = 'SET_BOOKING'
export const SET_WORKING_BOOKING = 'SET_WORKING_BOOKING'
export const REMOVE_BOOKING = 'REMOVE_BOOKING'

export const APPEND_BOOKING = 'APPEND_BOOKING'
export const SAVE_BOOKING = 'SAVE_BOOKING'
export const UPDATE_BOOKING = 'UPDATE_BOOKING'
export const DELETE_BOOKING = 'DELETE_BOOKING'
