export const SET_MEETING_ROOM_BOOKINGS = 'SET_MEETING_ROOM_BOOKINGS'
export const GET_MEETING_ROOM_BOOKINGS = 'GET_MEETING_ROOM_BOOKINGS'
export const GET_DAY_BOOKINGS = 'GET_DAY_BOOKINGS'

export const REMOVE_BOOKING = 'REMOVE_BOOKING'
export const UPDATE_BOOKING = 'UPDATE_BOOKING'
